micronaut:
    application:
        name: multitenancy-books
    server:
        port: 8081
hibernate:
    hbm2ddl:
        auto: 'update'
dataSources:
    sherlock:
        url: 'jdbc:h2:mem:sherlockDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
        username: 'sa'
        password: ''
        driverClassName: 'org.h2.Driver'
    watson:
        url: 'jdbc:h2:mem:watsonDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
        username: 'sa'
        password: ''
        driverClassName: 'org.h2.Driver'
grails:
    gorm:
        multiTenancy:
            mode: DATABASE
            tenantResolverClass: 'io.micronaut.multitenancy.gorm.HttpHeaderTenantResolver'