micronaut:
    application:
        name: bookinventory
    server:
        port: 8082
eureka:
    client:
        registration:
            enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
